// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpV8Ivwl7JJjXxJxmqnp2KBEkdkA2axkY',
    appId: '1:907472090614:web:130678955a14477aa383d7',
    messagingSenderId: '907472090614',
    projectId: 'dentist-app-5ec82',
    authDomain: 'dentist-app-5ec82.firebaseapp.com',
    databaseURL: 'https://dentist-app-5ec82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dentist-app-5ec82.appspot.com',
    measurementId: 'G-QZ1TYYFWEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmEj4Udq3ngwmJAEr5CTEtxtcz1oXrbsQ',
    appId: '1:907472090614:android:ce224ad4ba4f5201a383d7',
    messagingSenderId: '907472090614',
    projectId: 'dentist-app-5ec82',
    databaseURL: 'https://dentist-app-5ec82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dentist-app-5ec82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm-aeCJ3zcuaQV-FUokLh8mB339JyMECM',
    appId: '1:907472090614:ios:d306e0d673645c83a383d7',
    messagingSenderId: '907472090614',
    projectId: 'dentist-app-5ec82',
    databaseURL: 'https://dentist-app-5ec82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dentist-app-5ec82.appspot.com',
    iosBundleId: 'com.example.dentistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm-aeCJ3zcuaQV-FUokLh8mB339JyMECM',
    appId: '1:907472090614:ios:d306e0d673645c83a383d7',
    messagingSenderId: '907472090614',
    projectId: 'dentist-app-5ec82',
    databaseURL: 'https://dentist-app-5ec82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dentist-app-5ec82.appspot.com',
    iosBundleId: 'com.example.dentistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpV8Ivwl7JJjXxJxmqnp2KBEkdkA2axkY',
    appId: '1:907472090614:web:54a83ed8eca5d7bba383d7',
    messagingSenderId: '907472090614',
    projectId: 'dentist-app-5ec82',
    authDomain: 'dentist-app-5ec82.firebaseapp.com',
    databaseURL: 'https://dentist-app-5ec82-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dentist-app-5ec82.appspot.com',
    measurementId: 'G-DJFLYNMC54',
  );

}